#!/usr/bin/env bash

set -e

git --version

# Prompt immediately for sudo, and keep it alive while the install script runs
sudo -v
while true; do
  sudo -n true
  sleep 60
  kill -0 "$$" || exit
done &>/dev/null &

if [[ "$(uname -p)" == "arm" ]]; then
  if [[ -f /Library/Apple/usr/share/rosetta/rosetta ]]; then
    echo "Rosetta already installed."
  else
    echo "Installing Rosetta..."
    sudo softwareupdate --install-rosetta --agree-to-license
  fi
fi

if [[ -e /opt/homebrew/bin/brew || -e /usr/local/bin/brew ]]; then
  echo "Homebrew already installed."
else
  echo "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [[ -e /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -e /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

if hash jq &>/dev/null; then
  echo "jq already installed."
else
  echo "Installing jq..."
  brew install jq
fi

if hash mas &>/dev/null; then
  echo "mas already installed."
else
  echo "Installing mas..."
  brew install mas
fi

echo "Sign in to the app store first."
mas open
open "x-apple.systempreferences:com.apple.preferences.AppleIDPrefPane"

read -p "Have you signed in? [yn] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  echo "Unable to continue without app store sign in."
  exit 1
fi

if [[ -z "$GH_USER" ]]; then
  echo -n "GitHub user: "
  read GH_USER
fi

if [[ -z "$GH_USER" ]]; then
  echo "GH_USER not defined."
  exit 1
fi

DOTFILES_PATH="$HOME/grit/github.com/$GH_USER/dotfiles"

if [[ -d "$DOTFILES_PATH" ]]; then
  echo "Pulling $GH_USER/dotfiles..."
  pushd "$DOTFILES_PATH" &>/dev/null
  git pull
  popd &>/dev/null
else
  echo "Cloning $GH_USER/dotfiles..."
  git clone "git@github.com:$GH_USER/dotfiles.git" "$DOTFILES_PATH"
fi

if [[ -e "$HOME/dotfiles" ]]; then
  echo "Dotfiles directory shortcut already exists."
else
  echo "Creating dotfiles directory shortcut..."
  ln -s "$DOTFILES_PATH" "$HOME/dotfiles"
fi

for FILE in "$HOME/dotfiles/setup/"*-*.bash; do
  source "$FILE"
done

echo "Installation complete. System must be restarted for some changes to take effect."
